const products=[
{id:1,name:"Pack Starter",desc:"Ressources essentielles pour débuter.",price:29},
{id:2,name:"Pack Premium",desc:"Une sélection complète de ressources.",price:59},
{id:3,name:"Guide Nova",desc:"Méthode pratique et structurée.",price:19}
];
const formations=[
{id:4,name:"Formation Débutant",desc:"Les bases expliquées simplement.",price:49},
{id:5,name:"Formation Pro",desc:"Passe au niveau supérieur.",price:89},
{id:6,name:"Masterclass Nova",desc:"Programme complet et approfondi.",price:129}
];
let cart=JSON.parse(localStorage.getItem("novaCart")||"[]");
const view=document.querySelector("#view");
function money(n){return n.toLocaleString("fr-FR",{style:"currency",currency:"EUR"})}
function toast(t){let x=document.querySelector("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1800)}
function save(){localStorage.setItem("novaCart",JSON.stringify(cart));document.querySelector("#cartCount").textContent=cart.length}
function card(p){return `<article class="card"><div class="product-img">ATELIER NOVA</div><h3>${p.name}</h3><p class="muted">${p.desc}</p><p class="price">${money(p.price)}</p><button class="btn" onclick="add(${p.id})">Ajouter au panier</button></article>`}
function add(id){let p=[...products,...formations].find(x=>x.id===id);cart.push(p);save();toast(p.name+" ajouté au panier")}
function home(){return `<section class="hero"><div><div class="eyebrow">Bienvenue chez Atelier Nova</div><h1>Apprends.<br>Crée.<br>Évolue.</h1><p>Une plateforme élégante pour découvrir des formations et des ressources numériques conçues pour t'aider à passer à l'action.</p><a class="btn" href="#/boutique">Découvrir la boutique</a></div><div class="hero-card"><div><div class="eyebrow">Nouveau</div><h2>Ton prochain projet commence ici.</h2><p>Des contenus simples, accessibles et pensés pour être utilisés immédiatement.</p></div></div></section><section class="section"><div class="section-head"><div><div class="eyebrow">Sélection</div><h2>Les incontournables</h2></div><a href="#/boutique">Tout voir →</a></div><div class="grid">${products.map(card).join("")}</div></section><section class="section"><div class="feature"><div><b>01 — Simple</b><p class="muted">Une expérience claire et sans complication.</p></div><div><b>02 — Accessible</b><p class="muted">Des ressources disponibles où que tu sois.</p></div><div><b>03 — Pratique</b><p class="muted">Du contenu pensé pour passer à l'action.</p></div></div></section>`}
function listing(title,arr,sub){return `<section class="page"><div class="eyebrow">Atelier Nova</div><h1>${title}</h1><p class="muted">${sub}</p><div class="grid" style="margin-top:40px">${arr.map(card).join("")}</div></section>`}
function cartPage(){if(!cart.length)return `<section class="page"><h1>Votre panier</h1><div class="empty"><h2>Votre panier est vide.</h2><p class="muted">Ajoutez une ressource pour commencer.</p><a class="btn" href="#/boutique">Voir la boutique</a></div></section>`;let total=cart.reduce((a,b)=>a+b.price,0);return `<section class="page"><h1>Votre panier</h1><div class="form" style="max-width:700px">${cart.map((p,i)=>`<div class="cart-row"><span>${p.name}</span><strong>${money(p.price)} <button onclick="removeItem(${i})" style="border:0;background:none;cursor:pointer">×</button></strong></div>`).join("")}<div class="cart-row"><strong>Total</strong><strong>${money(total)}</strong></div><button class="btn" onclick="checkout()">Passer la commande</button></div></section>`}
function removeItem(i){cart.splice(i,1);save();render()}
function checkout(){toast("Démo : paiement à connecter");}
function profile(){return `<section class="page"><div class="member"><aside class="side"><h3>MON COMPTE</h3><a href="#/profil">Tableau de bord</a><a href="#/profil">Mes achats</a><a href="#/profil">Mon profil</a><a href="#/aide">Assistance</a></aside><div class="dash"><div class="eyebrow">Espace personnel</div><h1>Bienvenue 👋</h1><p class="muted">Connecte-toi pour retrouver tes formations et tes achats.</p><div class="form"><label>Email</label><input type="email" placeholder="ton@email.com"><label>Mot de passe</label><input type="password" placeholder="••••••••"><button class="btn" onclick="toast('Connexion de démonstration')">Se connecter</button><a class="btn light" href="#/inscription">Créer un compte</a></div></div></div></section>`}
function signup(){return `<section class="page"><h1>Créer un compte</h1><div class="form"><label>Nom</label><input placeholder="Ton nom"><label>Email</label><input type="email" placeholder="ton@email.com"><label>Mot de passe</label><input type="password" placeholder="••••••••"><button class="btn" onclick="toast('Compte de démonstration créé')">Créer mon compte</button></div></section>`}
function help(){return `<section class="page"><div class="eyebrow">Support</div><h1>Centre d'aide</h1><div class="faq"><b>Comment acheter une formation ?</b><p class="muted">Ajoute simplement le produit au panier puis passe commande.</p></div><div class="faq"><b>Comment accéder à mes achats ?</b><p class="muted">Après connexion, tes contenus apparaissent dans ton espace personnel.</p></div><div class="faq"><b>Une question ?</b><p class="muted">Utilise le formulaire ci-dessous.</p></div><div class="form" style="margin-top:30px"><input placeholder="Ton email"><textarea rows="5" placeholder="Ta demande"></textarea><button class="btn" onclick="toast('Message envoyé en démonstration')">Envoyer</button></div></section>`}
function render(){let r=location.hash.slice(1)||"/";if(r==="/")view.innerHTML=home();else if(r==="/boutique")view.innerHTML=listing("La boutique",products,"Ressources numériques sélectionnées par Atelier Nova.");else if(r==="/formations")view.innerHTML=listing("Les formations",formations,"Apprends à ton rythme avec nos programmes.");else if(r==="/panier")view.innerHTML=cartPage();else if(r==="/profil")view.innerHTML=profile();else if(r==="/inscription")view.innerHTML=signup();else if(r==="/aide")view.innerHTML=help();else view.innerHTML=home();save();window.scrollTo(0,0)}
document.querySelector("#searchBtn").onclick=()=>{let q=prompt("Que recherches-tu ?");if(q)toast("Recherche : "+q)}
window.addEventListener("hashchange",render);render();